#!/bin/bash
#
# Example script for synchronizing between a fat_free_crm database and a
# MAPI folder.
#
set -e
set -v
#PY=/c/Python26/python
PY=python
CRMDB="development.sqlite3"
CRMPATH="apenwarr@crm:src/fat_free_crm/db/$CRMDB"

crampi()
{
	$PY crampi.py "$@"
}

# this seems to force Windows' disk caching to refresh, even over samba
sha1sum crampi.py cmd/*.py lib/*.py >/dev/null

#crampi mapi-export -b mapi '*Avery*/Contacts/Zippy'
#crampi mapi-export -b mapi2 'Public Folders/All*/Global Contacts'
#rsync -a "$CRMPATH" "$CRMDB"
#crampi crm-export -b crm "$CRMDB"
#crampi crm-export -b crm --merge mapi "$CRMDB"
#crampi crm-export -b crm -m mapi2 "$CRMDB"
#rsync -a "$CRMDB" "$CRMPATH"

crampi ffcrm -b c1 ../fat_free_crm/db/development.sqlite3
crampi ffcrm -b c2 ../fat_free_crm2/db/development.sqlite3
crampi ffcrm -b c1 -m c2 ../fat_free_crm/db/development.sqlite3
crampi ffcrm -b c2 -m c1 ../fat_free_crm2/db/development.sqlite3

set +v
echo
echo Success.
