#!/bin/bash
#
# Example script for synchronizing between a fat_free_crm database and a
# MAPI folder.
#
set -e
set -v
PY=/c/Python26/python
CRMDB="development.sqlite3"
CRMPATH="apenwarr@crm:src/fat_free_crm/db/$CRMDB"

# this seems to force Windows' disk caching to refresh, even over samba
sha1sum crampi.py cmd/*.py lib/*.py >/dev/null

$PY crampi.py mapi-export --branch mapi '*Avery*/Contacts/Zippy'
#$PY crampi.py mapi-export --branch mapi2 'Public Folders/All*/Global Contacts' -v
rsync -a "$CRMPATH" "$CRMDB"
$PY crampi.py crm-export --branch crm "$CRMDB"
$PY crampi.py crm-export --branch crm --merge mapi "$CRMDB"
#$PY crampi.py crm-export --branch crm --merge mapi2 "$CRMDB"
rsync -a "$CRMDB" "$CRMPATH"

set +v
echo
echo Success.
